### ISSUE TITLE
Azure cloud provider cluster fails to up when a Service Principal that has multiple subscriptions

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#318]
Refer to steps from: https://github.com/rancher/rancher/issues/28049

That issue refers to rke1, but the same thing applies here in rke2 now. The only difference is that was deployed with rancher, and this is being deployed without rancher. Logs are generally the same when viewing the kubelet.log file.

**Comment by brandond** [comment]
Is this a common occurrence? What is the correct behavior her - should it pick the first available subscription? Should it use a specific subscription that's passed in the config file?

rke1 uses some custom scripts to set up the Azure SDK and that's where this was fixed for rek1, but rke2 is just using the in-tree provider directly, so I suspect that this may be an upstream issue?

**Comment by rancher-max** [comment]
Yes this happens every time for me. One scenario we tried was:
1. Create cluster using azure cloud provider through rancher (and rke1) with multiple subscriptions
2. Take the config file from that cluster and provide it when bringing up the cloud provider for rke2 cluster

This still failed with the same error.
I agree that this is likely to be an upstream issue.

**Comment by brandond** [comment]
Just out of curiosity, does this work if you set the AZURE_SUBSCRIPTION_ID environment variable for RKE2?

**Comment by rancher-max** [comment]
I don't think I tried that scenario but I can report back later today on that hopefully

**Comment by brandond** [comment]
I am just blindly groping through the upstream code and came across [this](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/583), so I'm curious if it will help.

**Comment by rancher-max** [comment]
Progress was made, though still not working. Below are the different things I tried and their results. Full command list to install rke2 each time was:
```
sudo -i
wget https://github.com/rancher/rke2/releases/download/v1.18.8-beta19+rke2/rke2.linux-amd64 && \
sudo mv rke2.linux-amd64 /usr/local/bin/rke2 && \
sudo chmod u+x /usr/local/bin/rke2

vi config.conf
...
sudo rke2 server --cloud-provider-name=azure --cloud-provider-config="/root/config.conf" --write-kubeconfig-mode=644 --node-name=maxrke2cp 2>&1 &
```

---

**Scenario 1: Created VM and associated resources using the same subscription ID as would be used in the cloudprovider conf**
- When providing a simple conf file (only tenantId, aadClientId, aadClientSecret, and subscriptionId supplied), it gave the same `node not found` error even though this was all within the same subscription. 
- When I supplied a more in depth conf file, it didn't have a panic in the kubelet logs and appeared to bring the cluster up, with errors.
```json
{
    "tenantId": "REDACTED",
    "aadClientId": "REDACTED",
    "aadClientSecret": "REDACTED",
    "subscriptionId": "REDACTED",
    "resourceGroup": "docker-machine",
    "location": "westus",
    "subnetName": "docker-machine",
    "vnetName": "docker-machine-vnet",
    "vnetResourceGroup": "docker-machine",
    "primaryAvailabilitySetName": "maxrke2cp-as",
    "useInstanceMetadata": true
}
```
- The cluster is accessible through kubectl at this point, although kubelet logs have a lot of errors:
[azkubelet.log](https://github.com/rancher/rke2/files/5233708/azkubelet.log)
- The node is in Ready state
- kube-controller-manager pod continuously restarts, with a panic:
[kube-controller-manager.log](https://github.com/rancher/rke2/files/5233432/kube-controller-manager.log)

**Scenario 2: Attempted to use AZURE_SUBSCRIPTION_ID env variable**
- This appeared to have no effect, whether it was in a VM with the same subscription id or different.
- Tried with the simpler config file to no avail
- Tried with the larger config file to same results as listed above



**My Thoughts:**
- It seems likely at this point that this is actually working as expected and is failing due to both my lack of knowledge with Azure in general and the way we have it setup internally.
- I saw some documentation [here](https://kubernetes-sigs.github.io/cloud-provider-azure/install/configs/#host-network-resources-in-different-aad-tenant-and-subscription) that seems like it would resolve the error of multiple subscriptions that is mentioned in this issue. I have not tried this yet.

**Comment by brandond** [comment]
It's crashing deep in the route table configuration: https://github.com/kubernetes/legacy-cloud-providers/blob/release-1.18/azure/azure_routes.go#L145

Somehow it's getting past all the error checks but ending up with a nil routeTable. This makes me suspect that we are doing something wrong/unsupported/unexpected/otherwise unusual.

**Comment by rancher-max** [comment]
My gut feeling is the same: 
- I think rke2 is working correctly here. 
- The parameters are being taken correctly from the cloud-provider-config conf file.
- This is no longer an issue of just "multiple subscriptions" since the behavior is the same when using a single subscription

**Comment by rancher-max** [comment]
Need to validate these assumptions soon, but as just a testing task this may be valid for even 1.18.9. I feel more comfortable bumping the milestone out to November to have time to truly validate this and ensure it works as expected.

**Comment by rancher-max** [comment]
Tried a few more times and I still firmly believe the failures I am seeing are something to do with my lack of Azure knowledge.

- Using the information from above with the additional documented parameter in azure config.conf of `networkResourceSubscriptionId`, I was able to get the cluster mostly up and running. There are less errors and the `kube-controller-manager` and `kube-scheduler` pods are up and running after a couple of restarts. 
- The `rke2-coredns` pod is failing to come up as it is stuck in Pending state but all other pods are running successfully. I noticed the reason for that appeared to be a taint that is being added to the node:
```
$ kubectl describe node | grep -i taints
Taints:             node.kubernetes.io/network-unavailable:NoSchedule
```
Removing this taint allowed the coredns pod to begin running successfully. However, the taint is immediately added back on afterwards. I believe this is likely expected when using the Azure cloud provider so I am not concerned with that. I would probably need to add worker nodes to the cluster to allow the cluster to have schedulable nodes, or ensure all deployments had tolerations to ignore this taint.

Given the information above, I feel comfortable calling this closed and validated. I tested on version: `v1.18.10+rke2r1`
