### ISSUE TITLE
VSPHERE CPI  - HelmChartConfig Setting :  how to add the zone/region labels in vsphere.conf ?

### ISSUE THREAD

**Issue by seb-835** [rancher/rke2#3398]
**Environmental Info:**

RKE2 Version: 1.24.4+rke2r1
Node(s) CPU architecture, OS, and Version: 3.10.0-1160.71.1.el7.x86_64

**Describe the bug:**

From what i see in : 
https://github.com/rancher/rke2-charts/blob/main/charts/rancher-vsphere-cpi/rancher-vsphere-cpi/1.2.201/templates/configmap.yaml

there is no way to add the [Labels] setting like shown here : 
https://cloud-provider-vsphere.sigs.k8s.io/tutorials/kubernetes-on-vsphere-with-helm.html

Is it a missed  ? or the Rancher Vsphere CPI does not support Vsphere Zones and Regions ?

**Comment by brandond** [comment]
This should be fixed by https://github.com/rancher/rke2/pull/3356 - the upstream chart has been enhanced to add that section:
* https://github.com/rancher/vsphere-charts/pull/23

**Comment by seb-835** [comment]
Thanks @brandond , 
Until the fix released,
with cpi 1.13.0, if i manualy modify  the configmap to add the labels Block, and restart pods, does it will be used ?

**Comment by brandond** [comment]
yeah, but it would be reverted if the helm chart is updated.

**Comment by seb-835** [comment]
Unfortunattely, it does not work.
I have added the Labels to the config map, and check that cpi pods restarts
```
[Labels]
region = "k8s-region"
zone = "k8s-zone"
```
but the node are still missing the topology, zone and region labels :(  they do not pop.
so the csi can is not able to  find a vsphere datastore to create PV :( 
because topology constraints are not added to the parameters when trying to createVolume .

**Comment by seb-835** [comment]
Ignore last message  i find the way, i will put the solution after completing tests

**Comment by seb-835** [comment]
@brandond 

see  a missed in : https://github.com/rancher/rke2-charts/blob/main/charts/rancher-vsphere-csi/rancher-vsphere-csi/2.6.0-rancher101/templates/controller/deployment.yaml

if  user set  labels setting for role and zone topology , 
we have to manage the following setting that are comments now:

```
          args:
            - "--v=4"
            - "--timeout=300s"
            - "--csi-address=$(ADDRESS)"
            - "--kube-api-qps=100"
            - "--kube-api-burst=100"
            - "--leader-election"
            - "--default-fstype=ext4"
            # needed only for topology aware setup
            #- "--feature-gates=Topology=true"
            #- "--strict-topology"
          env:
```

**Comment by brandond** [comment]
@seb-835 can you link to the specific line where you see a problem?

Note that the charts come from another repo: https://github.com/rancher/vsphere-charts/blob/main/charts/rancher-vsphere-csi/templates/controller/deployment.yaml

**Comment by seb-835** [comment]
@brandond 
For  role and zone topology to work, we have to uncomment   Line 209 and 210

https://github.com/rancher/vsphere-charts/blob/bc2dd9eae26a3c0608822bfa64e833893db1a0e1/charts/rancher-vsphere-csi/templates/controller/deployment.yaml#L209
https://github.com/rancher/vsphere-charts/blob/bc2dd9eae26a3c0608822bfa64e833893db1a0e1/charts/rancher-vsphere-csi/templates/controller/deployment.yaml#L210


 to have :

```
            - "--feature-gates=Topology=true"
            - "--strict-topology"
```

**Comment by brandond** [comment]
ah ok, I see. So for the CSI chart, we need an additional option to enable and configure the topology support. That will have to wait until next release. Lets open another issue to track that. For now, we'll confirm that it is possible to set the topology config in the CPI and CSI configuration files.

**Comment by VestigeJ** [comment]
Confirming that the zone/region labels are correctly passed through:
using VERSION=v1.24.7-rc1+rke2r1

$ sudo cat vsphere-values.yaml
```
# /var/lib/rancher/rke2/server/manifests/vsphere-values.yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rancher-vsphere-cpi
  labels:
  namespace: kube-system
spec:
  valuesContent: |-
    vCenter:
      host: "i.be-hosting-labs.com"
      datacenters: "datacentre"
      username: "administrator@haveibeenpwned.com"
      password: "magestic-coasters"
      credentialsSecret:
        generate: true
      labels:
        generate: true
        zone: "mordor"
        region: "plauge-zone"
    cloudControllerManager:
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rancher-vsphere-csi
  namespace: kube-system
spec:
  valuesContent: |-
    vCenter:
      host: "i.be-hosting-labs.com"
      datacenters: "datacentre"
      username: "administrator@haveibeenpwned.com"
      password: "magestic-coasters"
      clusterId: "rke2"
      configSecret:
        configTemplate: |
         [Global]
         cluster-id = {{ required ".Values.vCenter.clusterId must be provided" (default .Values.vCenter.clusterId .Values.global.cattle.clusterId) | quote }}
         user = {{ .Values.vCenter.username | quote }}
         password = {{ .Values.vCenter.password | quote }}
         port = {{ .Values.vCenter.port | quote }}
         insecure-flag = {{ .Values.vCenter.insecureFlag | quote }}
         [VirtualCenter {{ .Values.vCenter.host | quote }}]
         datacenters = {{ .Values.vCenter.datacenters | quote }}
         [Labels]
         zone = "mordor"
         region = "plauge"
    storageClass:
      datastoreURL: "ds:///vmfs/volumes/bb8ddcb0-ccc3p0e3-arc7-thelade3efe3f/"
    csiController:
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
```

$ k describe -n kube-system cm/vsphere-cloud-config
```
Name:         vsphere-cloud-config
Namespace:    kube-system
Labels:       app.kubernetes.io/managed-by=Helm
              component=rancher-vsphere-cpi-cloud-controller-manager
              vsphere-cpi-infra=config
Annotations:  meta.helm.sh/release-name: rancher-vsphere-cpi
              meta.helm.sh/release-namespace: kube-system

Data
====
vsphere.yaml:
----
# Global properties in this section will be used for all specified vCenters unless overriden in VirtualCenter section.

global:
  secretName: "vsphere-ciao-cocoa"
  secretNamespace: "kube-system"
  port: 443
  insecureFlag: true

vcenter:
  "i.be-hosting-labs.com":
    server: "i.be-hosting-labs.com"
    user: administrator@haveibeenpwned.com
    password: "magestic-coasters"
    datacenters:
      - "i.be-hosting-labs.com"
labels:
  region: plauge
  zone: mordor


BinaryData
====

Events:  <none>
```


$ kg -n kube-system secret/vsphere-config-secret -o yaml | grep -i -e csi-vsphere | awk '{print $2}' | base64 -d
```
[Global]
cluster-id = "rke2"
user = "administrator@haveibeenpwned.com"
password = "magestic-coasters"
port = "443"
insecure-flag = "1"
[VirtualCenter "i.be-hosting-labs.com"]
datacenters = "i.be-hosting-labs.com"
[Labels]
zone = "mordor"
region = "plauge"
```

$ rke2 -v
```
rke2 version v1.24.7-rc1+rke2r1 (a9d978dbdb5a1f707296df28df7e7eb31c7dd6c2)
go version go1.18.1b7
```
