### ISSUE TITLE
Missing Pod level Metrics  v1.23.16+rke2r1

### ISSUE THREAD

**Issue by vicious26** [rancher/rke2#4370]
**Environmental Info:**
rke2 version v1.23.16+rke2r1 (0124f3b3a88575a77ae75778eb82ef87a7302fc7)
go version go1.19.5 X:boringcrypto

Node(s) CPU architecture, OS, and Version:
Linux k8s-master1-99129 5.4.0-148-generic #165-Ubuntu SMP Tue Apr 18 08:53:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration: Multi master 3 servers

**Describe the bug:**
Pod level level metrics under /metric/resources are 0
pod_memory_working_set_bytes
pod_cpu_usage_seconds_total
Output from:
```kubectl get --raw /api/v1/nodes/$NODE_NAME/proxy/metrics/resource```
<img width="1169" alt="image" src="https://github.com/rancher/rke2/assets/51975970/9b8570f5-211d-4490-9be6-f75a953c8bfa">
<img width="1169" alt="image" src="https://github.com/rancher/rke2/assets/51975970/e788f9c7-6aa3-4701-b1ba-af64742baeae">

```  {
   "podRef": {
    "name": "kube-controller-manager-k8s-master1-99129",
    "namespace": "kube-system",
    "uid": "57585a0305e4e46df816ebab263926f3"
   },
   "startTime": "2023-05-04T19:39:46Z",
   "containers": [
    {
     "name": "kube-controller-manager",
     "startTime": "2023-05-05T09:31:20Z",
     "cpu": {
      "time": "2023-06-14T22:17:00Z",
      "usageNanoCores": 4659351,
      "usageCoreNanoSeconds": 10776950266695
     },
     "memory": {
      "time": "2023-06-14T22:17:00Z",
      "workingSetBytes": 24297472
     },
     "rootfs": {
      "time": "2023-06-14T22:16:55Z",
      "availableBytes": 232858636288,
      "capacityBytes": 368766496768,
      "usedBytes": 81920,
      "inodesFree": 21520069,
      "inodes": 22937600,
      "inodesUsed": 27
     },
     "logs": {
      "time": "2023-06-14T22:17:00Z",
      "availableBytes": 232858636288,
      "capacityBytes": 368766496768,
      "usedBytes": 8192,
      "inodesFree": 21520069,
      "inodes": 22937600,
      "inodesUsed": 2
     }
    }
   ],
   "cpu": {
    "time": "2023-06-14T22:16:59Z",
    "usageNanoCores": 0,
    "usageCoreNanoSeconds": 0
   },
   "memory": {
    "time": "2023-06-14T22:16:59Z",
    "usageBytes": 0,
    "workingSetBytes": 0,
    "rssBytes": 0,
    "pageFaults": 0,
    "majorPageFaults": 0
   },
   "ephemeral-storage": {
    "time": "2023-06-14T22:17:00Z",
    "availableBytes": 232858636288,
    "capacityBytes": 368766496768,
    "usedBytes": 94208,
    "inodesFree": 21520069,
    "inodes": 22937600,
    "inodesUsed": 30
   },
   "process_stats": {
    "process_count": 0
   }
  },
```

Cluster was upgrade using SUC from RKE2 v1.21.9 -> RKE2 v1.23.16
pod level metrics reports "0" when upgraded to RKE2 v1.23.16

**Steps To Reproduce:**

- Installed RKE2: 
upgrade RKE2 cluster using SUC 1.21.9 -> 1.23.16

**Expected behavior:**

I should be able to see pod level resource metrics

**Actual behavior:**

pod level resource metrics are missing
**Additional context / logs:**

**Comment by brandond** [comment]
> upgrade RKE2 cluster using SUC 1.21.9 -> 1.23.16

This is not supported; you should step through intermediate minor releases: 1.21 -> 1.22 -> 1.23. Ref:
https://kubernetes.io/releases/version-skew-policy/#supported-component-upgrade-order

I'm not able to reproduce this:

```console
brandond@dev01:~$ kubectl get node -o wide
NAME            STATUS   ROLES                       AGE     VERSION           INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION    CONTAINER-RUNTIME
rke2-server-1   Ready    control-plane,etcd,master   2m26s   v1.23.16+rke2r1   172.17.0.3    <none>        Ubuntu 22.04.2 LTS   5.19.0-1019-aws   containerd://1.5.16-k3s2
brandond@dev01:~$ kubectl get --raw /api/v1/nodes/rke2-server-1/proxy/metrics/resource | grep -E 'pod_memory_working|pod_cpu_usage_seconds_total'
# HELP pod_cpu_usage_seconds_total [ALPHA] Cumulative cpu time consumed by the pod in core-seconds
# TYPE pod_cpu_usage_seconds_total counter
pod_cpu_usage_seconds_total{namespace="kube-system",pod="cloud-controller-manager-rke2-server-1"} 0.844071 1686782056517
pod_cpu_usage_seconds_total{namespace="kube-system",pod="etcd-rke2-server-1"} 3.741962 1686782050884
pod_cpu_usage_seconds_total{namespace="kube-system",pod="kube-apiserver-rke2-server-1"} 16.892985 1686782043589
pod_cpu_usage_seconds_total{namespace="kube-system",pod="kube-controller-manager-rke2-server-1"} 2.292635 1686782051042
pod_cpu_usage_seconds_total{namespace="kube-system",pod="kube-proxy-rke2-server-1"} 0.504198 1686782045323
pod_cpu_usage_seconds_total{namespace="kube-system",pod="kube-scheduler-rke2-server-1"} 0.821098 1686782041197
pod_cpu_usage_seconds_total{namespace="kube-system",pod="rke2-canal-2wz4l"} 4.57511 1686782057800
pod_cpu_usage_seconds_total{namespace="kube-system",pod="rke2-coredns-rke2-coredns-775c5b4bb4-zr98t"} 0.21218 1686782052753
pod_cpu_usage_seconds_total{namespace="kube-system",pod="rke2-coredns-rke2-coredns-autoscaler-695fc554c9-csgxj"} 0.081418 1686782049337
pod_cpu_usage_seconds_total{namespace="kube-system",pod="rke2-ingress-nginx-controller-6w44q"} 0.795827 1686782053038
pod_cpu_usage_seconds_total{namespace="kube-system",pod="rke2-metrics-server-644f588b5-lnnxk"} 0.687582 1686782045108
# HELP pod_memory_working_set_bytes [ALPHA] Current working set of the pod in bytes
# TYPE pod_memory_working_set_bytes gauge
pod_memory_working_set_bytes{namespace="kube-system",pod="cloud-controller-manager-rke2-server-1"} 2.4858624e+07 1686782056517
pod_memory_working_set_bytes{namespace="kube-system",pod="etcd-rke2-server-1"} 4.4601344e+07 1686782050884
pod_memory_working_set_bytes{namespace="kube-system",pod="kube-apiserver-rke2-server-1"} 2.62823936e+08 1686782043589
pod_memory_working_set_bytes{namespace="kube-system",pod="kube-controller-manager-rke2-server-1"} 5.5123968e+07 1686782051042
pod_memory_working_set_bytes{namespace="kube-system",pod="kube-proxy-rke2-server-1"} 1.2632064e+07 1686782045323
pod_memory_working_set_bytes{namespace="kube-system",pod="kube-scheduler-rke2-server-1"} 1.898496e+07 1686782041197
pod_memory_working_set_bytes{namespace="kube-system",pod="rke2-canal-2wz4l"} 1.3879296e+08 1686782057800
pod_memory_working_set_bytes{namespace="kube-system",pod="rke2-coredns-rke2-coredns-775c5b4bb4-zr98t"} 1.3320192e+07 1686782052753
pod_memory_working_set_bytes{namespace="kube-system",pod="rke2-coredns-rke2-coredns-autoscaler-695fc554c9-csgxj"} 5.173248e+06 1686782049337
pod_memory_working_set_bytes{namespace="kube-system",pod="rke2-ingress-nginx-controller-6w44q"} 1.345536e+08 1686782053038
pod_memory_working_set_bytes{namespace="kube-system",pod="rke2-metrics-server-644f588b5-lnnxk"} 1.7854464e+07 1686782045108
```

**Comment by vicious26** [comment]
we are using OS:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"
```

Output from ```mount | grep cgroup```
```
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup2 on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,name=systemd)
cgroup on /sys/fs/cgroup/rdma type cgroup (rw,nosuid,nodev,noexec,relatime,rdma)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
```

no errors in kublet but in containerd i see:
```
time="2023-06-08T18:44:52.784039496Z" level=error msg="collecting metrics for f3dd31ae0a3f5f12906fa3dfb3b2a95d0f7029c4ccda02d34c8a4448069d4af1" error="ttrpc: closed: unknown"
time="2023-06-08T19:21:52.156382239Z" level=error msg="collecting metrics for b7c9cc9a56f99e17c11bde4ea8f216b0b973d2dc4e564f2a8788120e479a2770" error="ttrpc: closed: unknown"
time="2023-06-08T20:53:52.240308238Z" level=error msg="collecting metrics for 1a9e0a21dde73bcaf29f6f79e34327eac1f9841ac52e4ee70f55731388b3862f" error="ttrpc: closed: unknown"
time="2023-06-08T22:52:58.318153017Z" level=error msg="collecting metrics for d478d7b5c36ef0481bd5d735b269afcb259e41c6cee155f06c509953d914bed2" error="ttrpc: closed: unknown"
time="2023-06-09T00:13:32.960194349Z" level=error msg="collecting metrics for 42a6909a4fe42edda82685eb1dd537a5b9686580c8044011fc421cbabcfd74bd" error="ttrpc: closed: unknown"
time="2023-06-09T01:08:57.372549095Z" level=error msg="collecting metrics for 80ae7465d9a2c817f4f7a3e4b8b4889afe4649b4f3f609b2a74c0d718562c13d" error="ttrpc: closed: unknown"
time="2023-06-09T05:40:54.600546732Z" level=error msg="collecting metrics for 4d7515e5ffaee882c850effcf7b39e2c5f4a59cc5bb638474d8bbd0f6388dc5a" error="ttrpc: closed: unknown"
time="2023-06-09T06:34:53.318045016Z" level=error msg="collecting metrics for be68dbf3dddb1591243f96a004a2fd9d623466064272ab0efe20236bdb0c906c" error="ttrpc: closed: unknown"
```

```
kubectl top pod -n kube-system
````
<img width="575" alt="image" src="https://github.com/rancher/rke2/assets/51975970/d1d9a7b8-4d2d-4921-b56c-7781fc98e776">

```
crictl stats <container>
```
<img width="614" alt="image" src="https://github.com/rancher/rke2/assets/51975970/7ea31a48-9c6e-4ffa-8948-321f29a6f7bb">

**Comment by brandond** [comment]
Ah, you're using hybrid cgroups - you have both v1 and v2 mounted. That is not well supported by containerd with the systemd cgroup driver; you should use only v1 or v2. Do you perhaps have `systemd.unified_cgroup_hierarchy=0` in your grub kernel args? If so I believe that, changing that to 1, or adding it with a value of 1, and rebooting the node, should resolve this.

**Comment by vicious26** [comment]
Thank you! looks like i'm able to see pod level metrics now after i enabled ```systemd.unified_cgroup_hierarchy=1``` in grub and settting ```SystemdCgroup = true``` in containerd config. Does my cgroup output look correct?

<img width="1035" alt="image" src="https://github.com/rancher/rke2/assets/51975970/7d8828f4-daaf-4180-9d53-20c25285782c">

**Comment by brandond** [comment]
Yep, thats what you want to see!

**Comment by vicious26** [comment]
We are leveraging containerd that comes with the rke2 but with custom config template that enables v2 runtime and now systemd cgroupv2. After i made the cgroup v2 change i am noticing these errors from host. specially when i try to restart rke2-server service using systemctl 

```Failed to allocate directory watch: Too many open files```

I update my ```max_user_watches``` to ```10488576``` but i still see that error.

**Comment by brandond** [comment]
> `Failed to allocate directory watch: Too many open files`
> 
> I update my `max_user_watches` to `10488576` but i still see that error.

How did you raise it? The best way is to add it to a file in `/etc/sysctl.d/` and then run `sysctl --system` to apply the changes.

**Comment by vicious26** [comment]
```
version = 2

[plugins]

  [plugins."io.containerd.grpc.v1.cri"]
    enable_selinux = false
    sandbox_image = "index.docker.io/rancher/pause:3.2"
    stream_server_address = "127.0.0.1"
    stream_server_port = "10010"

    [plugins."io.containerd.grpc.v1.cri".containerd]
      default_runtime_name = "nvidia"
      disable_snapshot_annotations = true
      snapshotter = "overlayfs"

      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]

        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
          runtime_type = "io.containerd.runc.v2"

          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
            SystemdCgroup = true


  [plugins."io.containerd.internal.v1.opt"]
    path = "/data/rancher/rke2/agent/containerd"
```

In the [doc](https://kubernetes.io/docs/concepts/architecture/cgroups/#migrating-cgroupv2) it notes that: ```The kubelet automatically detects that the OS is running on cgroup v2 and performs accordingly with no additional configuration required.``` But it doen't mention what happens to already running rke2 servers (server migrated to v2). so that's why i added in the containered config template.

I changed the max_user_watches in /etc/sysctl.conf
