### ISSUE TITLE
rke2-ingress-nginx-controller does not become ready on SUSE Linux Enterprise 15 SP 2

### ISSUE THREAD

**Issue by tgeek77** [rancher/rke2#744]
Status of kubectl get pods:

```
> kubectl get pods -n kube-system
NAME                                                 READY   STATUS      RESTARTS   AGE
etcd-cplane01                                        1/1     Running     1          5d
helm-install-rke2-canal-5xfh6                        0/1     Completed   0          5d
helm-install-rke2-coredns-cl9zk                      0/1     Completed   0          5d
helm-install-rke2-ingress-nginx-p8ttm                0/1     Completed   0          5d
helm-install-rke2-kube-proxy-z62n9                   0/1     Completed   0          5d
helm-install-rke2-metrics-server-b6686               0/1     Completed   0          5d
kube-apiserver-cplane01                              1/1     Running     1          5d
kube-controller-manager-cplane01                     1/1     Running     1          5d
kube-proxy-26f7h                                     1/1     Running     1          5d
kube-scheduler-cplane01                              1/1     Running     1          5d
nginx-deployment-66b6c48dd5-8tq5b                    1/1     Running     1          4d23h
nginx-deployment-66b6c48dd5-fjp4d                    1/1     Running     1          4d23h
nginx-deployment-66b6c48dd5-jjv4v                    1/1     Running     1          4d23h
rke2-canal-fpgj9                                     2/2     Running     3          5d
rke2-coredns-rke2-coredns-6cd96645d6-fslz6           1/1     Running     1          5d
rke2-ingress-nginx-controller-54946dd48f-qww7g       0/1     Running     0          95m
rke2-ingress-nginx-default-backend-5795954f8-bg2t8   1/1     Running     1          5d
rke2-metrics-server-5f9b5757dc-h7wpz                 1/1     Running     1          5d
```

Excerpt from logs from rke2-ingress-nginx-controller:

```
2021/03/03 12:01:57 [notice] 18645#18645: signal process started
2021/03/03 12:01:57 [alert] 18645#18645: kill(26, 1) failed (13: Permission denied)
nginx: [alert] kill(26, 1) failed (13: Permission denied)
W0303 12:01:57.474626       9 queue.go:130] requeuing kube-system/kube-scheduler, err exit status 1
2021/03/03 12:01:57 [notice] 18645#18645: signal process started
2021/03/03 12:01:57 [alert] 18645#18645: kill(26, 1) failed (13: Permission denied)
nginx: [alert] kill(26, 1) failed (13: Permission denied)
I0303 12:02:00.740808       9 controller.go:137] Configuration changes detected, backend reload required.
E0303 12:02:00.790235       9 controller.go:149] Unexpected failure reloading the backend:
exit status 1
2021/03/03 12:02:00 [notice] 18653#18653: signal process started
2021/03/03 12:02:00 [alert] 18653#18653: kill(26, 1) failed (13: Permission denied)
nginx: [alert] kill(26, 1) failed (13: Permission denied)
W0303 12:02:00.790251       9 queue.go:130] requeuing kube-system/rke2-coredns-rke2-coredns, err exit status 1
2021/03/03 12:02:00 [notice] 18653#18653: signal process started
2021/03/03 12:02:00 [alert] 18653#18653: kill(26, 1) failed (13: Permission denied)
nginx: [alert] kill(26, 1) failed (13: Permission denied)
```

**Comment by Martin-Weiss** [comment]
Do you have apparmor disabled?

**Comment by tgeek77** [comment]
No, but then I disabled it and rebooted to test if that's the cause.  Same output.

**Comment by Martin-Weiss** [comment]
Ok - any CIS profile used? Do you see something in describe pod?

**Comment by brandond** [comment]
What version are you running? This was fixed in #680 and #681.

**Comment by Oats87** [comment]
@brandond should this be an issue with apparmor disabled though?

**Comment by brandond** [comment]
`kill(26, 1) failed (13: Permission denied)` is exactly that issue. I suspect it perhaps was not effectively disabled.

**Comment by Oats87** [comment]
I never said #680 or #681 did not fix this issue or that they were not "this issue", but was asking in regards to the comment here: https://github.com/rancher/rke2/issues/744#issuecomment-789695099 that stated the same failure was occurring even with `apparmor` disabled.

**Comment by Martin-Weiss** [comment]
Just as a quick side-note - in my deployments I have apparmor running and deployed and I am using the cis-1.5 profile.
I do NOT have this issue in my environments and I see this:
```

rancher-master-03:~ # aa-status
apparmor module is loaded.
50 profiles are loaded.
50 profiles are in enforce mode.
   /usr/bin/lessopen.sh
   /usr/lib/apache2/mpm-prefork/apache2
   /usr/lib/apache2/mpm-prefork/apache2//DEFAULT_URI
   /usr/lib/apache2/mpm-prefork/apache2//HANDLING_UNTRUSTED_INPUT
   /usr/lib/apache2/mpm-prefork/apache2//phpsysinfo
   /usr/lib/colord
   /usr/lib/dovecot/anvil
   /usr/lib/dovecot/auth
   /usr/lib/dovecot/config
   /usr/lib/dovecot/deliver
   /usr/lib/dovecot/dict
   /usr/lib/dovecot/dovecot-auth
   /usr/lib/dovecot/dovecot-lda
   /usr/lib/dovecot/dovecot-lda//sendmail
   /usr/lib/dovecot/imap
   /usr/lib/dovecot/imap-login
   /usr/lib/dovecot/lmtp
   /usr/lib/dovecot/log
   /usr/lib/dovecot/managesieve
   /usr/lib/dovecot/managesieve-login
   /usr/lib/dovecot/pop3
   /usr/lib/dovecot/pop3-login
   /usr/lib/dovecot/ssl-params
   /usr/lib/dovecot/stats
   /usr/sbin/dnsmasq
   /usr/sbin/dnsmasq//libvirt_leaseshelper
   apache2
   apache2//DEFAULT_URI
   apache2//HANDLING_UNTRUSTED_INPUT
   apache2//phpsysinfo
   avahi-daemon
   cri-containerd.apparmor.d
   dovecot
   identd
   klogd
   lsb_release
   mdnsd
   nmbd
   nscd
   ntpd
   nvidia_modprobe
   nvidia_modprobe//kmod
   ping
   smbd
   smbldap-useradd
   smbldap-useradd///etc/init.d/nscd
   syslog-ng
   syslogd
   traceroute
   winbindd
0 profiles are in complain mode.
19 processes have profiles defined.
19 processes are in enforce mode.
   /usr/local/bin/kube-scheduler (3789) cri-containerd.apparmor.d
   /usr/local/bin/kube-controller-manager (3796) cri-containerd.apparmor.d
   /usr/local/bin/kube-apiserver (3822) cri-containerd.apparmor.d
   /usr/local/bin/etcd (3834) cri-containerd.apparmor.d
   /usr/bin/dumb-init (5696) cri-containerd.apparmor.d
   /nginx-ingress-controller (5746) cri-containerd.apparmor.d
   /coredns (5748) cri-containerd.apparmor.d
   /usr/local/nginx/sbin/nginx (5832) cri-containerd.apparmor.d
   /usr/local/nginx/sbin/nginx (5852) cri-containerd.apparmor.d
   /usr/local/nginx/sbin/nginx (5853) cri-containerd.apparmor.d
   /usr/local/nginx/sbin/nginx (5854) cri-containerd.apparmor.d
   /usr/local/nginx/sbin/nginx (5855) cri-containerd.apparmor.d
   /usr/local/nginx/sbin/nginx (5856) cri-containerd.apparmor.d
   /bin/system-upgrade-controller (6245) cri-containerd.apparmor.d
   /bin/busybox (6526) cri-containerd.apparmor.d
   /bin/bash (6583) cri-containerd.apparmor.d
   /bin/bash (6954) cri-containerd.apparmor.d
   /usr/bin/backup-restore-operator (7007) cri-containerd.apparmor.d
   /usr/sbin/nscd (1163) nscd
0 processes are in complain mode.
0 processes are unconfined but have a profile defined.

```

**Comment by brandond** [comment]
@Oats87 right and based on our previous testing with QA this did not manifest when AppArmor was disabled, since the permission error comes from apparmor signal mediation... which makes me suspect it was not comprehensively disabled on the system in question.

**Comment by tgeek77** [comment]
I reinstalled SLE on my VM so I would have a clean system. First, I stopped and disabled AppArmor using `systemctl disable --now apparmor` and then I ran the installer. It worked this time. However, this isn't a good workaround. Will we see a AppArmor profile for RKE2 or should I also open a bug with the SLES team for this?

**Comment by Martin-Weiss** [comment]
> I reinstalled SLE on my VM so I would have a clean system. First, I stopped and disabled AppArmor using `systemctl disable --now apparmor` and then I ran the installer. It worked this time. However, this isn't a good workaround. Will we see an AppArmor profile for RKE2 or should I also open a bug with the SLES team for this?

You have to check with aa-status if apparmor is really stopped and profiles are disabled. AFAIK the systemctl stop does NOT do an aa-teardown.. (at least that was the case some time ago). If you want to disable apparmor for sure you can use the kernel command line apparmor=0. But - the better way might be to deliver proper apparmor profiles with containerd and other components as part of RKE2... not sure if this is required for CIS / FIPS profiles anyway..

**Comment by tgeek77** [comment]
After I disabled apparmor using systemctl before I deployed, the issue wasn't repeatable. I don't think I can write in a training manual that you must first disable apparmor before continuing the installation.

**Comment by tgeek77** [comment]
I opened https://bugzilla.suse.com/show_bug.cgi?id=1183170 on the SLES Dev side.

**Comment by brandond** [comment]
Just reposting because it appears to have been missed:

> What version are you running? This was fixed in #680 and #681.

**Comment by tgeek77** [comment]
I am using the latest version of RKE2 using the quick start instructions: https://docs.rke2.io/install/quickstart/ without a custom config.yaml. My SLES 15sp2 is patched to the latest version.

**Comment by brandond** [comment]
Can you confirm that `kubectl get nodes -o wide` says `v1.4.3-k3s3` for the containerd version?

**Comment by tgeek77** [comment]
```> kubectl get nodes -o wide
NAME       STATUS   ROLES         AGE   VERSION          INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                              KERNEL-VERSION         CONTAINER-RUNTIME
cplane01   Ready    etcd,master   21h   v1.19.8+rke2r1   172.99.1.11   <none>        SUSE Linux Enterprise Server 15 SP2   5.3.18-24.49-default   containerd://1.4.3-k3s3
```

**Comment by brandond** [comment]
That version has includes a cherry-pick of the suse-authored fix from @cyphar at https://github.com/containerd/containerd/pull/4467 so if that doesn't resolve all the issues with AppArmor then we're going to need to do more research.

**Comment by Martin-Weiss** [comment]
This is interesting - I do NOT have the problem (I am using cis-1.5 profile) and it seems that I have an earlier version of rke2!

```
NAME             STATUS   ROLES         AGE     VERSION          INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                              KERNEL-VERSION         CONTAINER-RUNTIME
s-vz-lev-kt011   Ready    etcd,master   3d17h   v1.19.7+rke2r1   10.11.6.11    10.11.6.11    SUSE Linux Enterprise Server 15 SP2   5.3.18-24.49-default   containerd://1.4.3-k3s2

```


```
 /usr/local/bin/rke2 --version
rke2 version v1.19.7+rke2r1 (d1430ad44dc162f15a54d093439c20ffb91f559b)
go version go1.15.5b5

```

**Comment by tgeek77** [comment]
I just set up an entirely new cluster from scratch. Issue is not repeating. Will try again tomorrow from scratch and till close the issue if it is not repeatable.

**Comment by tgeek77** [comment]
I confirmed that this is nor longer happening with the latest version of RKE2
