### ISSUE TITLE
`node-local-dns pod stuck in the `Init` state

### ISSUE THREAD

**Issue by mgfritch** [rancher/rke2#8230]
**Environmental Info:**
RKE2 Version:

rke2 version v1.33.0+rke2r1 (a9a0c194cbd38117b034ddd09ff7a4da0c8efe46)
go version go1.24.2 X:boringcrypto

Node(s) CPU architecture, OS, and Version: 
Linux host1 5.14.21-150500.55.44-default #1 SMP PREEMPT_DYNAMIC Mon Jan 15 10:03:40 UTC 2024 (cc7d8b6) x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

1 server

**Describe the bug:**

`node-local-dns pod` fails to start when `nodelocal` is enabled via CoreDNS 1.42.100 chart

**Steps To Reproduce:**

1. Install RKE2 with the CoreDNS 1.42.100 chart
2. Enable `nodelocal` in the CoreDNS chart
```
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-coredns
  namespace: kube-system
spec:
  valuesContent: |-
    nodelocal:
      enabled: true
```

**Expected behavior:**
`rke2-coredns` and `node-local-dns` pods are Running. 

**Actual behavior:**
The `node-local-dns pod remains in the Init state.

```
$ kubectl -n kube-system get pods | grep dns
helm-install-rke2-coredns-vrd5m                         0/1     Completed   0               12s
node-local-dns-4hxnt                                    0/1     Init:0/1    0               10s
rke2-coredns-rke2-coredns-55fdcddf98-dchm5              0/1     Running     0               10s
rke2-coredns-rke2-coredns-autoscaler-7cb854bd65-8dl2x   1/1     Running     0               10
```

**Additional context / logs:**
The rke2-coredns service is only available via UDP, while the `wait-coredns` init container expects TCP

```
$ kubectl -n kube-system get service rke2-coredns-rke2-coredns
NAME                        TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
rke2-coredns-rke2-coredns   ClusterIP   10.43.0.10   <none>        53/UDP    4m50s

$ kubectl -n kube-system logs node-local-dns-4hxnt -c wait-coredns | head -2
nc: 10.43.0.10 (10.43.0.10:53): Network is unreachable
waiting for dns service
```

See also: https://github.com/coredns/helm/commit/d579bfc7359dba42e9baa2f9b2dd3fc377b51f43

**Comment by caroline-suse-rancher** [comment]
Hi @mgfritch, is this solved? Was it ever tested?

**Comment by heroes1412** [comment]
still bug in v1.33.5+rke2r1 or v1.34.1+rke2r1. new installation.
tried to revert to v1.31.6+rke2r1, node-local-dns cache is ok.

**Comment by mgfritch** [comment]
> Hi [@mgfritch](https://github.com/mgfritch), is this solved? Was it ever tested?

Hey @caroline-suse-rancher !
Yes, this was resolved in the June release cycle , but we still need QA to verify it:
- https://github.com/rancher/rke2-charts/pull/691
- https://github.com/rancher/rke2/pull/8366

> still bug in v1.33.5+rke2r1 or v1.34.1+rke2r1. new installation. tried to revert to v1.31.6+rke2r1, node-local-dns cache is ok.

@heroes1412  I assume your comment is related to https://github.com/rancher/rke2/issues/9003? Is this working for you after resolving the problems encountered with SELinux?

**Comment by heroes1412** [comment]
thanks @mgfritch , after manual install rke2-selinux rpm, rke2-server can start normally with "selinux: true" in config.yaml file.
```
[root@rke-server ~]# rpm -qa | grep rke2
rke2-selinux-0.21-1.el9.noarch
rke2-common-1.33.5~rke2r1-0.el9.x86_64
```

but when i try to restart rke2-server, i got mess:
```
journalctl -u rke2-server | grep selinux
Oct 08 23:43:50 rke-server rke2[772]: time="2025-10-08T23:43:50+07:00" level=warning msg="SELinux is enabled for rke2 but process is not running in context 'container_runtime_t', rke2-selinux policy may need to be applied"
```

already restarted os (oracle linux 9, uek kernel), still got the mess

dns-node-cache still not work

dont know why. This does not happen in an internet environment.

**Comment by mdrahman-suse** [comment]
# Validated on v1.33.5+rke2r1 and master branch commit ec342ed2

Unable to replicate as could not find any version of rke2 that pulls rke2-coredns 1.42.100 chart

Steps:
```
$ cat rke2-coredns-99.yaml
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-coredns
  namespace: kube-system
spec:
  valuesContent: |-
    nodelocal:
      enabled: true
```
- Copy above to manifests dir
```
sudo mkdir -p /var/lib/rancher/rke2/server/manifests
sudo vi rke2-coredns-99.yaml
sudo cp rke2-coredns-99.yaml /var/lib/rancher/rke2/server/manifests
```
- Install rke2
```
curl -sfL https://get.rke2.io --output install.sh; sudo chmod +x install.sh
sudo INSTALL_RKE2_VERSION=v1.33.5+rke2r1 ./install.sh
sudo systemctl enable rke2-server.service --now
sudo chmod 644 /etc/rancher/rke2/rke2.yaml
```
- Check nodes, pods status
```
export KUBECONFIG=/etc/rancher/rke2/rke2.yaml PATH=$PATH:/var/lib/rancher/rke2/bin:/opt/bin:/usr/local/bin
kubectl get nodes,pods -A
```
- Ensure cluster is up and running
- `node-local-dns` pod is running
- Check coredns service, should have TCP


### Validation
```
$ rke2 -v
rke2 version v1.34.1+dev.ec342ed2 (ec342ed28ac9e9c3378d69daab607f0dbaa7dbfd)
go version go1.24.6 X:boringcrypto
```
```
$ sudo cat /var/lib/rancher/rke2/data/v1.34.1-dev.ec342ed2-e18234db36f3/charts/rke2-coredns.yaml | grep rke2-coredns
  name: "rke2-coredns"
    helm.cattle.io/chart-url: "https://rke2-charts.rancher.io/assets/rke2-coredns/rke2-coredns-1.43.302.tgz"
```
```
$ kubectl get nodes,pods -A | grep dns
kube-system   pod/helm-install-rke2-coredns-6jhs9                         0/1     Completed           0          2m6s
kube-system   pod/node-local-dns-pf4h8                                    1/1     Running             0          113s
kube-system   pod/rke2-coredns-rke2-coredns-autoscaler-5fcf54974d-tgtbw   1/1     Running             0          113s
kube-system   pod/rke2-coredns-rke2-coredns-bd94c5787-98pvz               1/1     Running             0          113s
```
```
$ kubectl -n kube-system get service rke2-coredns-rke2-coredns
NAME                        TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)         AGE
rke2-coredns-rke2-coredns   ClusterIP   10.43.0.10   <none>        53/UDP,53/TCP   3m37s
```
```
$ kubectl -n kube-system logs pod/node-local-dns-pf4h8 -c wait-coredns | head -2
nc: udptest first write: Operation not permitted
waiting for dns service
```

**Comment by heroes1412** [comment]
hi @mdrahman-suse @mgfritch i think the problem is with cilium cni, when i use default cni (canal) everything works fine.
 And how about selinux in offline env?
```
journalctl -u rke2-server | grep selinux
Oct 08 23:43:50 rke-server rke2[772]: time="2025-10-08T23:43:50+07:00" level=warning msg="SELinux is enabled for rke2 but process is not running in context 'container_runtime_t', rke2-selinux policy may need to be applied"
```

=========with Canal CNI
```
[root@n1 ~]# kubectl get nodes,pods -A
NAME      STATUS   ROLES                       AGE     VERSION
node/n1   Ready    control-plane,etcd,master   2m44s   v1.33.5+rke2r1

NAMESPACE     NAME                                                       READY   STATUS      RESTARTS   AGE
kube-system   pod/cloud-controller-manager-n1                            1/1     Running     0          2m34s
kube-system   pod/etcd-n1                                                1/1     Running     0          2m34s
kube-system   pod/helm-install-rke2-canal-vqqx7                          0/1     Completed   0          2m31s
kube-system   pod/helm-install-rke2-coredns-vpp2g                        0/1     Completed   0          2m31s
kube-system   pod/helm-install-rke2-ingress-nginx-l96gx                  0/1     Completed   0          2m31s
kube-system   pod/helm-install-rke2-metrics-server-wwlkq                 0/1     Completed   0          2m31s
kube-system   pod/helm-install-rke2-runtimeclasses-wfbf8                 0/1     Completed   0          2m30s
kube-system   pod/helm-install-rke2-snapshot-controller-crd-mq65x        0/1     Completed   0          2m30s
kube-system   pod/helm-install-rke2-snapshot-controller-hm7rd            0/1     Completed   1          2m29s
kube-system   pod/kube-apiserver-n1                                      1/1     Running     0          2m34s
kube-system   pod/kube-controller-manager-n1                             1/1     Running     0          2m34s
kube-system   pod/kube-proxy-n1                                          1/1     Running     0          2m34s
kube-system   pod/kube-scheduler-n1                                      1/1     Running     0          2m34s
kube-system   pod/node-local-dns-zkfb8                                   1/1     Running     0          2m4s
kube-system   pod/rke2-canal-tslbq                                       2/2     Running     0          2m2s
kube-system   pod/rke2-coredns-rke2-coredns-6464f98784-kjqt2             1/1     Running     0          2m4s
kube-system   pod/rke2-coredns-rke2-coredns-autoscaler-67bb49dff-v4287   1/1     Running     0          2m4s
kube-system   pod/rke2-ingress-nginx-controller-nck5n                    1/1     Running     0          49s
kube-system   pod/rke2-metrics-server-75d485c65b-vk4j5                   1/1     Running     0          73s
kube-system   pod/rke2-snapshot-controller-696989ffdd-8x4x4              1/1     Running     0          71s
```

= =========with cilium cni with bellow config
```
cat rke2-cilium-99.yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    localRedirectPolicy: true
    localRedirectPolicies:
      enabled: true
    kubeProxyReplacement: true
    k8sServiceHost: 127.0.0.1
    k8sServicePort: 6443
```
```
cat rke2-coredns-99.yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-coredns
  namespace: kube-system
spec:
  valuesContent: |-
    nodelocal:
      enabled: true
      use_cilium_lrp: true
```
```
cat rke2-coredns.yaml
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  annotations:
    helm.cattle.io/chart-url: https://rke2-charts.rancher.io/assets/rke2-coredns/rke2-coredns-1.43.302.tgz
    rke2.cattle.io/inject-cluster-config: "true"
  name: rke2-coredns
  namespace: kube-system
spec:
  bootstrap: true
```
```
kubectl get pod -A
NAMESPACE     NAME                                                   READY   STATUS      RESTARTS     AGE
kube-system   cilium-7gx4c                                           1/1     Running     0            8m43s
kube-system   cilium-envoy-p6c5z                                     1/1     Running     0            8m43s
kube-system   cilium-operator-dc7697f8-7jcwq                         1/1     Running     0            8m43s
kube-system   etcd-n1                                                1/1     Running     0            11m
kube-system   helm-install-rke2-cilium-nqd9d                         0/1     Completed   0            8m50s
kube-system   helm-install-rke2-coredns-8h4f2                        0/1     Completed   5            12m
kube-system   helm-install-rke2-ingress-nginx-9c5bb                  0/1     Completed   0            12m
kube-system   helm-install-rke2-metrics-server-c25fb                 0/1     Completed   0            12m
kube-system   helm-install-rke2-runtimeclasses-h529g                 0/1     Completed   0            12m
kube-system   hubble-relay-ff8d445c-nrrcr                            0/1     Running     5 (4s ago)   8m43s
kube-system   hubble-ui-7677cbb7c-klp4b                              2/2     Running     0            8m43s
kube-system   kube-apiserver-n1                                      1/1     Running     0            11m
kube-system   kube-controller-manager-n1                             1/1     Running     0            11m
kube-system   kube-scheduler-n1                                      1/1     Running     0            11m
kube-system   node-local-dns-dxnvp                                   0/1     Init:0/1    0            8m3s
kube-system   rke2-coredns-rke2-coredns-6464f98784-982q6             1/1     Running     0            8m3s
kube-system   rke2-coredns-rke2-coredns-autoscaler-67bb49dff-zkssc   1/1     Running     0            8m3s
kube-system   rke2-ingress-nginx-controller-r8xf4                    1/1     Running     0            5m37s
kube-system   rke2-metrics-server-75d485c65b-2qx6d                   1/1     Running     0            6m2s
```

**Comment by mdrahman-suse** [comment]
Thanks @heroes1412, I was able to replicate the issue with 1.33.5+rke2r1 as mentioned with cilium
```
$ rke2 -v
rke2 version v1.33.5+rke2r1 (d1092839cf08cb901b1d40461b0fa6e7ae6f8fc4)
go version go1.24.6 X:boringcrypto

$ kubectl get nodes,pods -A | grep dns
kube-system   pod/helm-install-rke2-coredns-9qcrz                        0/1     Completed   2          5m27s
kube-system   pod/node-local-dns-m4pjv                                   0/1     Init:0/1    0          4m49s
kube-system   pod/rke2-coredns-rke2-coredns-6464f98784-nzgs4             1/1     Running     0          4m49s
kube-system   pod/rke2-coredns-rke2-coredns-autoscaler-67bb49dff-wcjv8   1/1     Running     0          4m49s

Normal   Scheduled        5m7s                   default-scheduler  Successfully assigned kube-system/node-local-dns-m4pjv to server1
  Warning  FailedMount      4m52s (x6 over 5m7s)   kubelet            MountVolume.SetUp failed for volume "kube-dns-config" : object "kube-system"/"kube-dns" not registered
  Warning  FailedMount      4m52s (x6 over 5m7s)   kubelet            MountVolume.SetUp failed for volume "config-volume" : object "kube-system"/"node-local-dns" not registered
  Warning  NetworkNotReady  4m44s (x13 over 5m8s)  kubelet            network is not ready: container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
  Normal   Pulling          4m30s                  kubelet            Pulling image "rancher/hardened-dns-node-cache:1.26.0-build20250909"
  Normal   Pulled           4m23s                  kubelet            Successfully pulled image "rancher/hardened-dns-node-cache:1.26.0-build20250909" in 6.89s (6.89s including waiting). Image size: 23252622 bytes.
  Normal   Created          4m23s                  kubelet            Created container: wait-coredns
  Normal   Started          4m23s                  kubelet            Started container wait-coredns

$ kubectl logs -n kube-system pod/node-local-dns-m4pjv -c wait-coredns | head -3
waiting for dns service
nc: 10.43.0.10 (10.43.0.10:53): Operation not permitted
waiting for dns service
```

So apparently this may have not worked as expected. Creating a new issue for cilium as it is failing with that specific CNI: https://github.com/rancher/rke2/issues/9056
CC @mgfritch

**Comment by mgfritch** [comment]
@heroes1412 @mdrahman-suse Thanks!

Let's close this issue (based on the validation https://github.com/rancher/rke2/issues/8230#issuecomment-3387335410) and track the new issue found by @heroes1412 via https://github.com/rancher/rke2/issues/9056
